export const types = {
  APP_CONFIG: {
    SCROLL: "APP_CONFIG/SCROLL",
    SCROLL_STACK: "APP_CONFIG/SCROLL_STACK",
    ABOUT_MODAL: "APP_CONFIG/ABOUT_MODAL",
    CONTACT_MODAL: "APP_CONFIG/CONTACT_MODAL",
    FRONTEND_MODAL: "APP_CONFIG/FRONTEND_MODAL",
    BACKEND_MODAL: "APP_CONFIG/BACKEND_MODAL",
    DATABASE_MODAL: "APP_CONFIG/DATABASE_MODAL",
    MOBILE_MODAL: "APP_CONFIG/MOBILE_MODAL",
    SERVER_MODAL: "APP_CONFIG/SERVER_MODAL",
  },
};
