export const types = {
  APP_CONFIG: {
    SCROLL: "APP_CONFIG/SCROLL",
    SCROLL_STACK: "APP_CONFIG/SCROLL_STACK",
    ABOUT_MODAL: "APP_CONFIG/ABOUT_MODAL",
    CONTACT_MODAL: "APP_CONFIG/CONTACT_MODAL",
  },
};
